# Generated by Django 4.2.1 on 2023-08-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoothData2019",
            fields=[
                (
                    "polling_booth_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("polling_booth_name", models.CharField(max_length=255)),
                ("winner_2014", models.CharField(max_length=255)),
                (
                    "first_runner_up_other_than_INC_and_BJP",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("margin_percent", models.FloatField()),
                ("margin", models.IntegerField()),
                ("total", models.IntegerField()),
                ("BJP_votes", models.IntegerField()),
                ("BJP_percent_vote", models.FloatField()),
                ("INC_votes", models.IntegerField()),
                ("INC_percent_votes", models.FloatField()),
                ("Dadarao_Kisansro_Uikey", models.IntegerField()),
                ("Deashmukh_Nilesh_Madhukarrao", models.IntegerField()),
                ("Sandeep_Dilip_Kale", models.IntegerField()),
                ("Prashant_Gokuldasji_Kathane", models.IntegerField()),
                ("Dnyaneshwar_Narayan_Maddavi", models.IntegerField()),
                ("Arvind_Shamrao_Lillore", models.IntegerField()),
                ("Arun_Ajabrao_Pachare", models.IntegerField()),
                ("Topale_Rupchand_Bhuraji", models.IntegerField()),
                ("Tarachand_Sonbaji_Nehare", models.IntegerField()),
                ("Dilip_Shamraoji_Potfode", models.IntegerField()),
                ("Nikose_Wasudeo_Shamrao", models.IntegerField()),
                ("Sanjay_Dhondbaji_Tule", models.IntegerField()),
                ("wapnil_Alias_Bala_Rameshrao_Jagtap", models.IntegerField()),
                ("NOTA", models.IntegerField()),
                ("no_of_tendered_votes", models.IntegerField()),
                ("no_of_votes_gotten_by_3rd_parties", models.IntegerField()),
            ],
        ),
    ]
