# Generated by Django 4.2.1 on 2023-08-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0003_rename_boothdata2019_boothdata2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothdata2014",
            name="no_of_votes_gotten_by_3rd_parties",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
