# Generated by Django 4.2.1 on 2023-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0004_alter_boothdata2014_no_of_votes_gotten_by_3rd_parties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothdata2014",
            name="Arun_Ajabrao_Pachare",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Arvind_Shamrao_Lillore",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="BJP_percent_vote",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="BJP_votes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Dadarao_Kisansro_Uikey",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Deashmukh_Nilesh_Madhukarrao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Dilip_Shamraoji_Potfode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Dnyaneshwar_Narayan_Maddavi",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="INC_percent_votes",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="INC_votes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="NOTA",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Nikose_Wasudeo_Shamrao",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Prashant_Gokuldasji_Kathane",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Sandeep_Dilip_Kale",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Sanjay_Dhondbaji_Tule",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Tarachand_Sonbaji_Nehare",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="Topale_Rupchand_Bhuraji",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="margin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="margin_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="no_of_tendered_votes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2014",
            name="wapnil_Alias_Bala_Rameshrao_Jagtap",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
