# Generated by Django 4.2.1 on 2023-08-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0006_alter_boothdata2014_no_of_tendered_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothdata2014",
            name="margin",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
