# Generated by Django 4.2.1 on 2023-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0007_alter_boothdata2014_margin"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoothData2019",
            fields=[
                (
                    "polling_booth_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("polling_booth_name", models.CharField(max_length=255)),
                ("winner_2019", models.CharField(max_length=255)),
                ("margin_percent", models.FloatField()),
                ("margin", models.IntegerField()),
                ("total_voters", models.IntegerField()),
                ("BJP_votes", models.IntegerField()),
                ("BJP_percent_votes", models.FloatField()),
                ("INC_votes", models.IntegerField()),
                ("INC_percent_votes", models.FloatField()),
                ("Adv_Chandrashekar_Dongre", models.IntegerField()),
                ("Topale_Rupachand", models.IntegerField()),
                ("Rahul_Parasanji_Tayde", models.IntegerField()),
                ("Sanjay_Ambadas_Wankhede", models.IntegerField()),
                ("Avinash_Suresh_Badhiye", models.IntegerField()),
                ("Deepak_M_Madavi", models.IntegerField()),
                ("Dilip_Shamraoji_Potfode", models.IntegerField()),
                ("Vilas_Vinayakrao_Kailuke", models.IntegerField()),
                ("NOTA", models.IntegerField()),
                ("no_of_votes_got_by_3rd_parties", models.IntegerField()),
                ("BJP_booth_strength", models.CharField(max_length=255)),
                ("INC_booth_strength", models.CharField(max_length=255)),
            ],
        ),
    ]
