# Generated by Django 4.2.1 on 2023-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0008_boothdata2019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothdata2019",
            name="BJP_percent_votes",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
