# Generated by Django 4.2.1 on 2023-08-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poll", "0010_alter_boothdata2019_inc_percent_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothdata2019",
            name="BJP_percent_votes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="boothdata2019",
            name="INC_percent_votes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
